// Automatically generated by astro-icon
// 0c2d0aab44e585cb8f18c2a5baf4f5ae9ef8dec7a83c23fac01490dbe0e2d440

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow-right"
		| "bolt"
		| "chevron-down"
		| "code"
		| "discord"
		| "email"
		| "github"
		| "jay3332"
		| "layers"
		| "link"
		| "linkedin"
		| "lock";
}