// Automatically generated by astro-icon
// 51129c32f2f8f8f3d9d4e2457ca7bc20c075623e310f2cd78cb4b4eddc639761

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow-right"
		| "bolt"
		| "chevron-down"
		| "chevron-right"
		| "code"
		| "discord"
		| "email"
		| "github"
		| "jay3332"
		| "languages/c"
		| "languages/java"
		| "languages/kotlin"
		| "languages/python"
		| "languages/rust"
		| "languages/typescript"
		| "layers"
		| "link"
		| "linkedin"
		| "lock";
}