// Automatically generated by astro-icon
// 183d2ef4f110765fa4619471b515ddc185ea403c2d7a8cad7961a43bba2b4753

declare module 'virtual:astro-icon' {
	export type Icon = 
		| "arrow-right"
		| "bolt"
		| "chevron-down"
		| "code"
		| "discord"
		| "email"
		| "github"
		| "jay3332"
		| "languages/c"
		| "languages/java"
		| "languages/kotlin"
		| "languages/python"
		| "languages/rust"
		| "languages/typescript"
		| "layers"
		| "link"
		| "linkedin"
		| "lock";
}